name: CD

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'pipelines/*.yaml'

jobs:
  detect-deleted-regions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files in the last commit
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- pipelines/*.yaml)
          echo "CHANGED_FILES=${CHANGED_FILES}"
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Detect deleted regions or files from the last commit
        run: |
          DELETED_REGIONS=$(for file in ${{ env.CHANGED_FILES }}; do
            if git ls-tree -r HEAD --name-only | grep -q "$file"; then
              old_regions=$(git show HEAD~1:$file | yq '.regions[]' || echo "")
              new_regions=$(yq '.regions[]' $file || echo "")
              deleted_regions=$(comm -23 <(echo "$old_regions" | sort) <(echo "$new_regions" | sort))
              if [ -n "$deleted_regions" ]; then
                echo "$deleted_regions"
              fi
            fi
          done | paste -sd "," -)
          echo "DELETED_REGIONS=${DELETED_REGIONS}"
          echo "DELETED_REGIONS=${DELETED_REGIONS}" >> $GITHUB_ENV
