on:
  push:
    paths:
      - 'pipelines/*.yaml'
      - 'pipelines/*.yml'

jobs:
  detect-deleted-regions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'pipelines/*.yaml pipelines/*.yml'

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Detect deleted regions or files
        run: |
          REGION_DELETED="false"
          DELETED_REGIONS=""
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing file: $file"
            
            # Check if the file was deleted
            if ! git ls-tree -r HEAD --name-only | grep -q "$file"; then
              echo "File $file was deleted in this commit."
              continue
            fi

            # Get regions from the previous commit
            git show HEAD~1:$file > old_file.yaml || echo "" > old_file.yaml

            old_regions=$(yq '.regions[]' old_file.yaml || echo "")
            new_regions=$(yq '.regions[]' $file || echo "")

            # Find deleted regions
            deleted_regions=$(comm -23 <(echo "$old_regions" | sort) <(echo "$new_regions" | sort))

            if [ -n "$deleted_regions" ]; then
              REGION_DELETED="true"
              DELETED_REGIONS="$deleted_regions"
            fi
          done

          # Set environment variables for deleted regions
          echo "REGION_DELETED=$REGION_DELETED" >> $GITHUB_ENV
          echo "DELETED_REGIONS=$DELETED_REGIONS" >> $GITHUB_ENV
          
          # Output the environment variables for logging purposes (optional)
          echo "Deleted regions: $DELETED_REGIONS"
          echo "Region deleted: $REGION_DELETED"
